# Generated by Django 6.0.4 on 2026-05-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('referee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('referee_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'referees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results_J1',
            fields=[
                ('match_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('home_team_id', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team_id', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('home_team_goal', models.IntegerField()),
                ('away_team_goal', models.IntegerField()),
                ('referee', models.CharField(max_length=50)),
                ('referee_id', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=1)),
                ('winner_team_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'results_J1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('team_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
    ]
