# Generated by Django 6.0.4 on 2026-08-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('referee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('referee_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'referees',
            },
        ),
        migrations.CreateModel(
            name='ResultsJ1',
            fields=[
                ('match_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('home_team_id', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team_id', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('home_team_goal', models.IntegerField()),
                ('away_team_goal', models.IntegerField()),
                ('referee', models.CharField(max_length=50)),
                ('referee_id', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=1)),
                ('winner_team_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'results_J1',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('team_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
        migrations.DeleteModel(
            name='Results_J1',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
